# Generated by Django 5.2.2 on 2025-06-21 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="LineBindingStatus",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("line_id", models.CharField(max_length=64, unique=True)),
                ("step", models.CharField(default="none", max_length=32)),
                (
                    "temp_username",
                    models.CharField(blank=True, max_length=150, null=True),
                ),
            ],
        ),
    ]
