# Generated by Django 5.2.2 on 2025-06-11 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="is_company",
            field=models.BooleanField(default=False),
        ),
    ]
