# Generated by Django 5.2.2 on 2025-06-21 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0002_alter_user_is_company"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="line_id",
            field=models.CharField(blank=True, max_length=64, null=True, unique=True),
        ),
    ]
