# Generated by Django 5.2.2 on 2025-06-21 12:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0003_user_line_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="line_id",
        ),
    ]
