# Generated by Django 5.2.2 on 2025-06-21 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0005_user_line_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="temp_username",
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
